apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "faktory.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "faktory.name" . }}
    helm.sh/chart: {{ include "faktory.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- (.Files.Glob "files/*.toml").AsConfig | nindent 2 }}
